"""Unit tests for specmcp.auth.pkce."""

from __future__ import annotations

import base64
import hashlib

import pytest

from specmcp.auth.pkce import generate_verifier, generate_challenge


# ---------------------------------------------------------------------------
# generate_verifier
# ---------------------------------------------------------------------------


def test_verifier_is_43_chars():
    """token_urlsafe(32) produces 43 URL-safe base64 characters."""
    v = generate_verifier()
    assert len(v) == 43


def test_verifier_url_safe_alphabet():
    """Verifier must only contain URL-safe base64 characters (no +, /, =)."""
    v = generate_verifier()
    allowed = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_")
    assert all(c in allowed for c in v), f"Unexpected chars in verifier: {v!r}"


def test_verifier_unique():
    """Two verifiers must never be equal (256-bit entropy)."""
    v1 = generate_verifier()
    v2 = generate_verifier()
    assert v1 != v2


def test_verifier_not_empty():
    v = generate_verifier()
    assert v


# ---------------------------------------------------------------------------
# generate_challenge
# ---------------------------------------------------------------------------


def test_challenge_is_s256():
    """Challenge must be BASE64URL(SHA256(verifier)) — RFC 7636 §4.2."""
    verifier = "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk"
    expected_digest = hashlib.sha256(verifier.encode("ascii")).digest()
    expected = base64.urlsafe_b64encode(expected_digest).rstrip(b"=").decode("ascii")
    assert generate_challenge(verifier) == expected


def test_challenge_no_padding():
    """Challenge must not contain '=' padding characters."""
    v = generate_verifier()
    c = generate_challenge(v)
    assert "=" not in c


def test_challenge_url_safe_alphabet():
    """Challenge must only contain URL-safe base64 characters."""
    v = generate_verifier()
    c = generate_challenge(v)
    allowed = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_")
    assert all(ch in allowed for ch in c), f"Unexpected chars in challenge: {c!r}"


def test_challenge_is_43_chars():
    """SHA-256 produces 32 bytes → base64url (no padding) is always 43 chars."""
    v = generate_verifier()
    c = generate_challenge(v)
    assert len(c) == 43


def test_challenge_deterministic():
    """Same verifier must always produce the same challenge."""
    v = generate_verifier()
    assert generate_challenge(v) == generate_challenge(v)


def test_challenge_distinct_for_different_verifiers():
    """Different verifiers must produce different challenges."""
    v1 = generate_verifier()
    v2 = generate_verifier()
    assert generate_challenge(v1) != generate_challenge(v2)


def test_challenge_empty_verifier_raises():
    """Empty verifier must raise ValueError."""
    with pytest.raises(ValueError, match="empty"):
        generate_challenge("")


def test_verifier_challenge_round_trip():
    """A verifier generated by generate_verifier() works with generate_challenge()."""
    v = generate_verifier()
    c = generate_challenge(v)
    # Independently re-derive the challenge and compare
    digest = hashlib.sha256(v.encode("ascii")).digest()
    expected = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")
    assert c == expected
